services:
  app:
    build: .
    ports:
      - "3000:3000"
    # Crucial: Tells Docker to read your local environment keys
    env_file:
      - .env
    # Fallback default value if .env is missing inside Docker
    environment:
      - PORT=3000
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
      - ./package.json:/app/package.json
      - ./pnpm-workspace.yaml:/app/pnpm-workspace.yaml
      - ./pnpm-lock.yaml:/app/pnpm-lock.yaml
      - .npmrc:/app/.npmrc
    command: sh -c "corepack enable && pnpm install --config.confirm-modules-purge=false && pnpm dev"
